[package]
name = "hyprland_workspaces"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
derive_more = "2.1.0"
hyprland = "=0.4.0-beta.3"
once_cell = "1.19.0"
rust-ini = "0.21.3"
helpers = { path = "../helpers" }
