[package]
name = "bar"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.9"
tempfile = "3.23.0"
wayland-client = "0.31.11"
wayland-protocols-wlr = {version = "0.3.9", features = ["client"]}
