[package]
name = "bar"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
derive_more = "2.1.0"
hyprland = "=0.4.0-beta.3"
memmap2 = "0.9.9"
rust-ini = "0.21.3"
tempfile = "3.23.0"
wayland-client = "0.31.11"
wayland-protocols-wlr = {version = "0.3.9", features = ["client"]}
