[package]
name = "tray"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = "5.12.0"
tokio = { version = "1.48.0", features = ["full"] }
zvariant = "5.8.0"
serde = { version = "1.0.228", features = ["derive"] }
helpers = { path = "../helpers" }
logger = { path = "../logger" }
